### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by anewage** [LinuxFest/LinuxFestival#23]
* Add `becoming a sponsor` option in the landing page.
* Add `Submit your CV` option in the landing page.
* Remove old sections.
* Add a form for sponsors.

**Comment by allahrezaei** [comment]
اينقدر ايميل نده ديوث

**Comment by ssheikholeslami** [comment]
@allahrezaei با گیت‌هاب بلدی کار کنی؟ میدونی خودت زدی که برات ایمیل بیاد؟ بلدی Unwatch کنی؟
